import { soundService } from './sound';

export interface PetReactionProfile {
  reactionKey: string;
  animationClass: string;
  actionLabel: string;
  soundEffectLabel: string;
  particleEmojis: string[];
  particleColors: string[];
  dialogues: string[];
  triggerSound: () => void;
}

export const PET_REACTIONS: Record<string, PetReactionProfile> = {
  // COMMON
  'starter-doge': {
    reactionKey: 'wag',
    animationClass: 'animate-pet-wag',
    actionLabel: 'wags tail and barks happily!',
    soundEffectLabel: 'Bark! Woof!',
    particleEmojis: ['🦴', '🐾', '⭐', '🐶'],
    particleColors: ['#fbbf24', '#f59e0b', '#d97706'],
    dialogues: [
      "Much math! Such multiply! Very 12x12! 🐕",
      "Woof! Did you know 5 × 5 = 25? Like 5 packs of yummy dog treats!",
      "Tail wag level 100%! Keep solving, math champion!",
      "Woof woof! 7 × 8 = 56! Never forget 5, 6, 7, 8!",
    ],
    triggerSound: () => soundService.playPetBark(),
  },
  'pixel-cat': {
    reactionKey: 'pounce',
    animationClass: 'animate-pet-pounce',
    actionLabel: 'arches back and swats a yarn ball!',
    soundEffectLabel: 'Purrrr! Meow!',
    particleEmojis: ['🐟', '🧶', '✨', '🐾'],
    particleColors: ['#f97316', '#fb923c', '#fdba74'],
    dialogues: [
      "Purrrrr! 9 × 7 = 63! Meow-velous thinking!",
      "Cats have 9 lives, and 9 × 9 = 81! That's a lot of lives!",
      "*purrs loudly against your hand* You're doing paw-some!",
      "Meow! 6 × 6 = 36! As smooth as silk whiskers!",
    ],
    triggerSound: () => soundService.playPetPurr(),
  },
  'chunky-piggy': {
    reactionKey: 'wiggle',
    animationClass: 'animate-pet-wiggle',
    actionLabel: 'snorts and does a muddy wiggle dance!',
    soundEffectLabel: 'Oink! Snort!',
    particleEmojis: ['🍎', '🌾', '💖', '🐷'],
    particleColors: ['#f472b6', '#fb7185', '#fda4af'],
    dialogues: [
      "Oink oink! Muddy math is the best math! 🐖",
      "Snort! 4 × 8 = 32! That's 32 crunchy red apples!",
      "That tickles! Blox Bux bonus rolling in the mud!",
      "Oink! 3 × 9 = 27! Never underestimate a smart piggy!",
    ],
    triggerSound: () => soundService.playPetOink(),
  },
  'tiny-bunny': {
    reactionKey: 'hops',
    animationClass: 'animate-pet-hops',
    actionLabel: 'does triple zoomie hops and wiggles nose!',
    soundEffectLabel: 'Boing! Squeak!',
    particleEmojis: ['🥕', '⭐', '🌸', '🐰'],
    particleColors: ['#cbd5e1', '#f8fafc', '#fb923c'],
    dialogues: [
      "Boing boing! Double-double trick: for 4 × 6, double 6 to 12, then double to 24!",
      "Hop hop hop! You're multiplying faster than a speeding bunny!",
      "*twitches nose* I smell correct answers and juicy carrots!",
      "3 × 7 = 21! Hop over to the next challenge!",
    ],
    triggerSound: () => soundService.playPetSqueak(),
  },
  'baby-bear': {
    reactionKey: 'bear-hug',
    animationClass: 'animate-pet-roar',
    actionLabel: 'stands tall and offers a warm bear hug!',
    soundEffectLabel: 'Grrr-hug! Roar!',
    particleEmojis: ['🍯', '🐻', '💛', '⭐'],
    particleColors: ['#b45309', '#d97706', '#f59e0b'],
    dialogues: [
      "Bear hug incoming! You are un-bear-ably smart! 🍯",
      "Sweet as honey! 8 × 8 = 64! Ate and ate and got sick on the floor!",
      "*grrs softly* Bear paw high-five for that awesome streak!",
      "Hibernate? No way! We have multiplication tables to conquer!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'yellow-duck': {
    reactionKey: 'waddle',
    animationClass: 'animate-pet-wiggle',
    actionLabel: 'flaps wings and does a happy duck waddle!',
    soundEffectLabel: 'Quack! Quack!',
    particleEmojis: ['🪶', '💦', '🐥', '🌟'],
    particleColors: ['#facc15', '#fde047', '#38bdf8'],
    dialogues: [
      "Quack! 10 × 6 = 60! Just drop a zero like a smooth pond splash! 🦆",
      "Waddle waddle! You're ducking great at multiplication!",
      "Quack quack! Water off a duck's back—no problem can stop us!",
      "2 × 12 = 24! That's a double dozen ducklings!",
    ],
    triggerSound: () => soundService.playPetSqueak(),
  },
  'green-dino': {
    reactionKey: 'stomp',
    animationClass: 'animate-pet-stomp',
    actionLabel: 'stomps tiny feet creating mini tremors!',
    soundEffectLabel: 'RAWR! Stomp!',
    particleEmojis: ['🌿', '🦖', '💥', '🌋'],
    particleColors: ['#22c55e', '#16a34a', '#84cc16'],
    dialogues: [
      "RAWR! Dino crunch! I eat tough math equations for breakfast! 🦖",
      "STOMP! 7 × 7 = 49! As massive as a Brachiosaurus!",
      "Tiny arms, HUGE brain! Keep stomping those multiplication tables!",
      "Fossil facts: 6 × 8 = 48! Absolutely prehistoric brilliance!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'mini-cow': {
    reactionKey: 'cow-bell',
    animationClass: 'animate-pet-wag',
    actionLabel: 'bobs head ringing its golden cowbell!',
    soundEffectLabel: 'Moo! Ding-dong!',
    particleEmojis: ['🥛', '🔔', '🍀', '🐮'],
    particleColors: ['#e2e8f0', '#94a3b8', '#fbbf24'],
    dialogues: [
      "Mooo-velous job! Ring the bell for +20% bonus coins! 🔔",
      "Holy cow! 11 × 9 = 99! Eleven's twin magic at work!",
      "*chimes bell* Udder perfection in your math answers!",
      "Moo! 5 × 12 = 60! As easy as grazing on sweet clover!",
    ],
    triggerSound: () => soundService.playPetChime(),
  },

  // RARE
  'cyber-bunny': {
    reactionKey: 'zap',
    animationClass: 'animate-pet-zap',
    actionLabel: 'emits neon cyan electric pulses from visor!',
    soundEffectLabel: 'Bzzzt! Cyber ping!',
    particleEmojis: ['⚡', '🔋', '🌐', '🐇'],
    particleColors: ['#06b6d4', '#22d3ee', '#38bdf8'],
    dialogues: [
      "Cyber overclock active! Calculating products in 0.001 seconds! ⚡",
      "Neon logic engaged: 12 × 12 = 144! Maximum grid capacity!",
      "Bzzzzt! +30% Blox Bux uploaded to your wallet!",
      "Quantum hop! Numbers are simply data waiting to be decoded!",
    ],
    triggerSound: () => soundService.playPetZap(),
  },
  'speedy-cheetah': {
    reactionKey: 'cheetah-dash',
    animationClass: 'animate-pet-slide',
    actionLabel: 'rockets into hyper-speed leaving speed lines!',
    soundEffectLabel: 'Whoosh! Zoom!',
    particleEmojis: ['💨', '🐆', '⚡', '🔥'],
    particleColors: ['#f59e0b', '#eab308', '#f97316'],
    dialogues: [
      "VROOOOM! Fast as lightning! Nobody can out-speed your calculations! 🐆",
      "Mach 5 math! 8 × 6 = 48 before the timer even started!",
      "Turbines boosted! You're cruising through these tables!",
      "Speed streak bonus active! Keep those gears turning!",
    ],
    triggerSound: () => soundService.playPetSlide(),
  },
  'panda-monk': {
    reactionKey: 'panda-spin',
    animationClass: 'animate-pet-spin',
    actionLabel: 'executes a tranquil 360 kung-fu martial kick!',
    soundEffectLabel: 'Haaa-ya! Whirr!',
    particleEmojis: ['🎋', '☯️', '🐼', '🍃'],
    particleColors: ['#64748b', '#94a3b8', '#22c55e'],
    dialogues: [
      "Mastery is not rushed, grasshopper: 9 × 8 = 72! 🎋",
      "Breathe in focus, breathe out wrong answers! Peace and multiplication!",
      "A peaceful mind multiplies with supreme clarity!",
      "Bamboo strength: 7 × 6 = 42! The answer to everything!",
    ],
    triggerSound: () => soundService.playPetTrick(),
  },
  'frost-penguin': {
    reactionKey: 'penguin-slide',
    animationClass: 'animate-pet-slide',
    actionLabel: 'drops onto belly and slides leaving frost crystals!',
    soundEffectLabel: 'Swoosh! Brrr!',
    particleEmojis: ['❄️', '🧊', '🐧', '🧤'],
    particleColors: ['#38bdf8', '#7dd3fc', '#bae6fd'],
    dialogues: [
      "Waddle slide! Brrr, keep your cool and remember 8 × 8 = 64! ❄️",
      "Sub-zero focus! The frost penguin glides over hard tables!",
      "Ice cool calculations! That answer was slippery smooth!",
      "Chill out! Multiplication is just repeated addition with style!",
    ],
    triggerSound: () => soundService.playPetSlide(),
  },
  'cyber-fox': {
    reactionKey: 'fox-laser',
    animationClass: 'animate-pet-pounce',
    actionLabel: 'activates red laser targeting sight and winks!',
    soundEffectLabel: 'Pew! Target locked!',
    particleEmojis: ['🎯', '🦊', '🔴', '✨'],
    particleColors: ['#f97316', '#ef4444', '#f59e0b'],
    dialogues: [
      "Target locked! Correct solution acquired in high definition! 🦊",
      "Laser focus: 9 × 4 = 36! Bullseye on every problem!",
      "Smart like a fox, sharp like a laser beam!",
      "Sensors detect 100% mathematical accuracy!",
    ],
    triggerSound: () => soundService.playPetGlitch(),
  },
  'electric-hamster': {
    reactionKey: 'hamster-zap',
    animationClass: 'animate-pet-zap',
    actionLabel: 'sparks lightning from red cheeks with hyper energy!',
    soundEffectLabel: 'Zzzzzap! Pika-buzz!',
    particleEmojis: ['⚡', '🐹', '💡', '✨'],
    particleColors: ['#eab308', '#facc15', '#fde047'],
    dialogues: [
      "ZAP! 6 × 7 = 42! High voltage brain power charging up! ⚡",
      "Cheek sparks tingling! You're electrifying the leaderboard!",
      "BZZZZT! 10x tables just add a zero—pure electric magic!",
      "Volt burst! +40% Blox Bux bonus powered up!",
    ],
    triggerSound: () => soundService.playPetZap(),
  },
  'space-koala': {
    reactionKey: 'koala-spin',
    animationClass: 'animate-pet-spin',
    actionLabel: 'floats into zero-gravity with a shining space helmet!',
    soundEffectLabel: 'Beep! Zero-G!',
    particleEmojis: ['🚀', '🌌', '🐨', '⭐'],
    particleColors: ['#818cf8', '#a5b4fc', '#c7d2fe'],
    dialogues: [
      "Houston, no problems here! 11 × 11 = 121! 🚀",
      "Floating in zero gravity! Math expands as big as the cosmos!",
      "*helmet radio crackle* You are cleared for launch, astronaut Bloxer!",
      "To infinity and multiplication! Orbiting around high scores!",
    ],
    triggerSound: () => soundService.playPetTrick(),
  },
  'ninja-frog': {
    reactionKey: 'frog-smoke',
    animationClass: 'animate-pet-hops',
    actionLabel: 'vanishes in a puff of smoke and reappears grinning!',
    soundEffectLabel: 'Poof! Nin-nin!',
    particleEmojis: ['💨', '🐸', '🗡️', '🍃'],
    particleColors: ['#10b981', '#34d399', '#6ee7b7'],
    dialogues: [
      "Poof! Secret ninja math technique: 12 × 4 = 48! 🥷",
      "Silent, swift, and mathematically lethal!",
      "Ribbit! The way of the multiplication ninja has no blind spots!",
      "Smokebomb! Master all 12 tables in the shadows!",
    ],
    triggerSound: () => soundService.playPetTrick(),
  },

  // EPIC
  'golden-lion': {
    reactionKey: 'lion-roar',
    animationClass: 'animate-pet-roar',
    actionLabel: 'puffs magnificent golden mane and roars like royalty!',
    soundEffectLabel: 'ROAAAAR! Majesty!',
    particleEmojis: ['👑', '🦁', '✨', '🏆'],
    particleColors: ['#eab308', '#f59e0b', '#d97706'],
    dialogues: [
      "ROAAAR! The King of Mathblox salutes your royal brilliance! 👑",
      "Regal rule: 7 × 7 = 49! Fit for a multiplication emperor!",
      "Golden courage fills your streak! Stand proud, champion!",
      "By royal decree, you earn +60% bonus Blox Bux on every victory!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'mecha-dragon': {
    reactionKey: 'dragon-fire',
    animationClass: 'animate-pet-roar',
    actionLabel: 'flaps metallic wings and vents green plasma fire!',
    soundEffectLabel: 'Kshhh! Plasma blast!',
    particleEmojis: ['🔥', '⚙️', '🐲', '💚'],
    particleColors: ['#10b981', '#22c55e', '#4ade80'],
    dialogues: [
      "SYSTEM STATUS: MATH COMPUTATION AT 100%! PLASMA BLAST! 🔥",
      "Cyber dragon core online: 12 × 8 = 96! Target eradicated!",
      "Mechanical wings deployed! Soaring above every math obstacle!",
      "Armor plating withstands all incorrect answers! Unstoppable!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'shadow-wolf': {
    reactionKey: 'wolf-howl',
    animationClass: 'animate-pet-roar',
    actionLabel: 'howls at a spectral violet crescent moon!',
    soundEffectLabel: 'Awooooo! Shadow pulse!',
    particleEmojis: ['🐺', '🌙', '💜', '🔮'],
    particleColors: ['#9333ea', '#a855f7', '#c084fc'],
    dialogues: [
      "AWOOOOO! The shadow pack hunts for 3-star table masteries! 🐺",
      "Night whispers: 8 × 9 = 72! The shadows guide your intuition!",
      "Eyes glowing purple in the dark! Your streak cannot be hidden!",
      "Shadow power surges! +70% Blox Bux bonus flowing through the ether!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'lava-golem': {
    reactionKey: 'magma-surge',
    animationClass: 'animate-pet-stomp',
    actionLabel: 'volcanic fissures glow bright orange with erupting embers!',
    soundEffectLabel: 'KABOOM! Magma rumbling!',
    particleEmojis: ['🌋', '🔥', '☄️', '💥'],
    particleColors: ['#e11d48', '#f43f5e', '#fb7185'],
    dialogues: [
      "MOLTEN CORE OVERHEATING! 6 × 9 = 54! PURE LIQUID FIRE! 🌋",
      "The floor is lava, but your math knowledge is solid diamond bedrock!",
      "RUMBLE! Volcanic math explosion adds +80% Bux bounty!",
      "No mistake can cool down this fiery multiplication streak!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'galaxy-slime': {
    reactionKey: 'slime-squish',
    animationClass: 'animate-pet-pounce',
    actionLabel: 'squishes flat like jelly and bounces with star ripples!',
    soundEffectLabel: 'Bloop-squish! Pop!',
    particleEmojis: ['🫧', '🌌', '⭐', '🟣'],
    particleColors: ['#8b5cf6', '#a78bfa', '#c4b5fd'],
    dialogues: [
      "Bloop! Squishy cosmic jelly absorbs all multiplication facts! 🫧",
      "Cosmic swirls inside my tummy: 9 × 12 = 108! Stardust delicious!",
      "*wobbles with planetary rings* You're delightfully out of this world!",
      "Squish-bounce! Bouncing straight to the top of the leaderboards!",
    ],
    triggerSound: () => soundService.playPetTrick(),
  },
  'astral-tiger': {
    reactionKey: 'tiger-strike',
    animationClass: 'animate-pet-pounce',
    actionLabel: 'slashes glowing starlight claw streaks through space!',
    soundEffectLabel: 'Slash! Starlight strike!',
    particleEmojis: ['🐯', '✨', '⚡', '💫'],
    particleColors: ['#f59e0b', '#d97706', '#fbbf24'],
    dialogues: [
      "Starlight claws unleash: 7 × 12 = 84! Celestial perfection! 🐯",
      "Prowling among constellations! Every correct answer shines like a nova!",
      "Stripe by stripe, table by table, you are mastering the entire cosmos!",
      "Astral instincts never fail: +90% Blox Bux multipliers active!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },

  // LEGENDARY
  'thunder-pegasus': {
    reactionKey: 'pegasus-lightning',
    animationClass: 'animate-pet-hops',
    actionLabel: 'rears up and flaps celestial wings summoning lightning!',
    soundEffectLabel: 'Thunder crash! Neigh!',
    particleEmojis: ['⚡', '🪽', '⛈️', '🦄'],
    particleColors: ['#06b6d4', '#38bdf8', '#e0f2fe'],
    dialogues: [
      "THUNDER CRACK! DOUBLE BLOX BUX UNLEASHED! ⚡",
      "Pegasus flight speed: 12 × 11 = 132! Electrifying accuracy!",
      "Galloping across storm clouds! Lightning illuminates your genius!",
      "2.0x MULTIPLIER GRANTED! You are unstoppable, winged champion!",
    ],
    triggerSound: () => soundService.playPetZap(),
  },
  'cyber-hydra': {
    reactionKey: 'hydra-bob',
    animationClass: 'animate-pet-wag',
    actionLabel: 'all three cybernetic serpent heads bob in unison!',
    soundEffectLabel: 'Hiss-sync! Tri-laser!',
    particleEmojis: ['🐍', '🤖', '💚', '⚡'],
    particleColors: ['#14b8a6', '#0d9488', '#2dd4bf'],
    dialogues: [
      "Head 1: '7 × 8 is...' Head 2: '56!' Head 3: 'GENIUS!' 🐍",
      "Three brains calculate three times faster than one! 2.1x Boost!",
      "Tri-laser synchronization: All 12 tables mapped into our cyber-drive!",
      "Hiss! Cut down one problem, three correct answers appear!",
    ],
    triggerSound: () => soundService.playPetGlitch(),
  },
  'golden-doge-supreme': {
    reactionKey: 'golden-shower',
    animationClass: 'animate-pet-wag',
    actionLabel: 'drops sunglasses down and showers pure gold coins!',
    soundEffectLabel: 'Cha-ching! WOW!',
    particleEmojis: ['💰', '👑', '🐕', '✨'],
    particleColors: ['#fbbf24', '#f59e0b', '#eab308'],
    dialogues: [
      "SUCH WEALTH! VERY GOLDEN! MUCH MULTIPLY! WOW! 🐕💎",
      "24-Karat Math Genius: 12 × 12 = 144 gold bars in your vault!",
      "*golden tail wag* 2.2x Blox Bux showering from the sky!",
      "Diamond collar gleaming! You're the richest math wizard in Robloxia!",
    ],
    triggerSound: () => soundService.playPetBark(),
  },
  'dark-reaper': {
    reactionKey: 'ghost-spook',
    animationClass: 'animate-pet-spin',
    actionLabel: 'fades into transparent blue mist and giggles playfully!',
    soundEffectLabel: 'Boooo-yah! Spooky chill!',
    particleEmojis: ['👻', '🔮', '💀', '💜'],
    particleColors: ['#64748b', '#475569', '#a855f7'],
    dialogues: [
      "Boooo-yah! Don't fear multiplication—7 × 8 = 56 is friendly! 👻",
      "Phase-shifting through tricky tables! Phantom power 2.3x active!",
      "*chilling ghostly whisper* You solved that with supernatural speed!",
      "Ethereal aura shields you from mistakes! Spectral math mastery!",
    ],
    triggerSound: () => soundService.playPetTrick(),
  },
  'neon-leviathan': {
    reactionKey: 'leviathan-breach',
    animationClass: 'animate-pet-slide',
    actionLabel: 'breaches out of glowing neon water with blowhole spray!',
    soundEffectLabel: 'Splash! Deep ocean roar!',
    particleEmojis: ['🐋', '🌊', '💧', '💙'],
    particleColors: ['#2563eb', '#3b82f6', '#60a5fa'],
    dialogues: [
      "OCEAN TITAN BREACH! Deep sea math powers activated! 🐋",
      "Tidal wave of products: 11 × 8 = 88! Deep ocean clarity!",
      "2.4x Ocean Titan boost surges through the math reefs!",
      "Singing the ancient whale song of the 12 multiplication tables!",
    ],
    triggerSound: () => soundService.playPetSplash(),
  },

  // MYTHIC
  'rainbow-unicorn': {
    reactionKey: 'unicorn-spiral',
    animationClass: 'animate-pet-spin',
    actionLabel: 'horn radiates a sparkling prismatic rainbow spiral!',
    soundEffectLabel: 'Twinkle-gleam! Starlight!',
    particleEmojis: ['🦄', '🌈', '⭐', '💖'],
    particleColors: ['#d946ef', '#ec4899', '#a855f7'],
    dialogues: [
      "COSMIC STAR POWER! Prismatic rainbow logic surrounds you! 🦄🌈",
      "Pure magic: 9 × 9 = 81! Horn glowing with celestial starlight!",
      "2.5x Cosmic multiplier! Dreams and multiplication facts come true!",
      "Galloping across rainbow bridges of knowledge! Pure brilliance!",
    ],
    triggerSound: () => soundService.playPetChime(),
  },
  'phoenix-fire': {
    reactionKey: 'phoenix-flare',
    animationClass: 'animate-pet-roar',
    actionLabel: 'erupts in radiant solar fire feathers and rises higher!',
    soundEffectLabel: 'Screeech! Solar blast!',
    particleEmojis: ['🦅', '🔥', '☀️', '✨'],
    particleColors: ['#ef4444', '#f97316', '#facc15'],
    dialogues: [
      "SOLAR BLAST! Reborn from the ashes of every challenge! 🔥",
      "Sun Phoenix radiance: 12 × 9 = 108! Burning through all doubts!",
      "2.7x Solar blast multiplier! Flying higher than the clouds!",
      "The fire of knowledge never goes out! Glorious mathematics!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'rainbow-dragon': {
    reactionKey: 'dragon-fire',
    animationClass: 'animate-pet-roar',
    actionLabel: 'spreads iridescent rainbow wings and breathes starlight!',
    soundEffectLabel: 'ROAAR! Prismatic blast!',
    particleEmojis: ['🐉', '🌈', '💎', '🔥'],
    particleColors: ['#ef4444', '#eab308', '#3b82f6'],
    dialogues: [
      "3.0x TRIPLE BLOX BUX! The mythical Rainbow Dragon bows to you! 🐉",
      "Prismatic breath: 12 × 12 = 144! The ultimate dragon multiplication!",
      "Ancient rainbow scales shimmer with mathematical supremacy!",
      "You hold the wisdom of all 12 tables! Legendary dragon master!",
    ],
    triggerSound: () => soundService.playPetRoar(),
  },
  'glitch-angel': {
    reactionKey: 'glitch-jitter',
    animationClass: 'animate-pet-zap',
    actionLabel: 'matrix glitch jitter scatters floating binary code!',
    soundEffectLabel: '0101-bzzzt! Angel chime!',
    particleEmojis: ['🪽', '👾', '0️⃣', '1️⃣'],
    particleColors: ['#a855f7', '#ec4899', '#06b6d4'],
    dialogues: [
      "ERROR 404: WRONG ANSWERS NOT FOUND IN SYSTEM! 🪽",
      "Divine Glitch Power: 3.2x multiplier rewriting reality!",
      "Binary wings flutter through the matrix! 101010 = Math Perfection!",
      "Glitch ascending! Breaking through the limits of calculation!",
    ],
    triggerSound: () => soundService.playPetGlitch(),
  },
  'diamond-titan': {
    reactionKey: 'titan-crystal',
    animationClass: 'animate-pet-stomp',
    actionLabel: 'crystalline core pulses blinding cyan light with floating gems!',
    soundEffectLabel: 'Pshhh-chime! Diamond resonance!',
    particleEmojis: ['💎', '💠', '🔷', '✨'],
    particleColors: ['#06b6d4', '#22d3ee', '#38bdf8'],
    dialogues: [
      "UNBREAKABLE DIAMOND TIER! 3.5x ULTIMATE GOD MULTIPLIER! 💎",
      "Diamond core resonance: 12 × 12 = 144! Impervious to all errors!",
      "Crystal facets reflect the entire 12x12 universe! You are invincible!",
      "THE PINNACLE OF MATHBLOX! Bow before the Diamond Blox Titan!",
    ],
    triggerSound: () => soundService.playPetChime(),
  },
};

export function getPetReactionProfile(petId: string): PetReactionProfile {
  if (PET_REACTIONS[petId]) {
    return PET_REACTIONS[petId];
  }
  return {
    reactionKey: 'wag',
    animationClass: 'animate-pet-wag',
    actionLabel: 'bounces happily beside you!',
    soundEffectLabel: 'Chirp! Yay!',
    particleEmojis: ['💖', '⭐', '✨', '🐾'],
    particleColors: ['#fbbf24', '#f472b6', '#38bdf8'],
    dialogues: [
      "You're doing great! Keep multiplying! 🌟",
      "I give you a Blox Bux bonus on every correct answer!",
      "High five! MathBlox champions never quit!",
    ],
    triggerSound: () => soundService.playPetHappy(),
  };
}
